using Banned.Qbittorrent.Models.Application;
using Banned.Qbittorrent.Models.Requests;
using Banned.Qbittorrent.Models.TorrentCreator;
using Banned.Qbittorrent.Serialization;

namespace Banned.Qbittorrent.Services;

/// <summary>
/// 提供 qBittorrent 种子创建任务相关服务。<br/>
/// Provides services for qBittorrent torrent creation tasks.
/// </summary>
public class TorrentCreatorService(NetService netService)
{
    private const string BaseUrl = "/api/v2/torrentcreator";

    /// <summary>
    /// 添加种子创建任务。<br/>
    /// Adds a torrent creation task.
    /// </summary>
    /// <param name="request">创建任务参数。<br/>Task creation parameters.</param>
    /// <param name="cancellationToken">取消请求的令牌。<br/>Token used to cancel the request.</param>
    /// <returns>创建的任务。<br/>The created task.</returns>
    public async Task<TorrentCreatorTask?> AddTask(CreateTorrentTaskRequest request,
                                                   CancellationToken        cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(request);
        var response = await netService.Post($"{BaseUrl}/addTask", request.ToDictionary(), ApiVersion.V2_10_4,
                                             ct : cancellationToken);
        return QBittorrentJsonSerializer.Deserialize<TorrentCreatorTask>(response);
    }

    /// <summary>
    /// 获取一个或全部种子创建任务的状态。<br/>
    /// Gets the status of one or all torrent creation tasks.
    /// </summary>
    /// <param name="taskId">任务 ID；为空时返回全部任务。<br/>Task ID; all tasks are returned when null.</param>
    /// <param name="cancellationToken">取消请求的令牌。<br/>Token used to cancel the request.</param>
    /// <returns>任务状态列表。<br/>Task status list.</returns>
    public async Task<List<TorrentCreatorTaskStatus>> GetStatuses(string?           taskId            = null,
                                                                  CancellationToken cancellationToken = default)
    {
        var parameters = new Dictionary<string, string>();

        if (!string.IsNullOrWhiteSpace(taskId)) parameters["taskID"] = taskId;

        var response =
            await netService.Post($"{BaseUrl}/status", parameters, ApiVersion.V2_10_4, ct : cancellationToken);
        return QBittorrentJsonSerializer.Deserialize<List<TorrentCreatorTaskStatus>>(response) ?? [];
    }

    /// <summary>
    /// 获取已完成任务生成的 .torrent 文件。<br/>
    /// Gets the .torrent file generated by a completed task.
    /// </summary>
    /// <param name="taskId">任务 ID。<br/>Task ID.</param>
    /// <param name="cancellationToken">取消请求的令牌。<br/>Token used to cancel the request.</param>
    /// <returns>.torrent 文件内容。<br/>The .torrent file content.</returns>
    public async Task<byte[]> GetTorrentFile(string taskId, CancellationToken cancellationToken = default)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(taskId);
        var parameters = new Dictionary<string, string> { { "taskID", taskId } };
        return await netService.PostBytes($"{BaseUrl}/torrentFile", parameters, ApiVersion.V2_10_4,
                                          ct : cancellationToken);
    }

    /// <summary>
    /// 删除种子创建任务。<br/>
    /// Deletes a torrent creation task.
    /// </summary>
    /// <param name="taskId">任务 ID。<br/>Task ID.</param>
    /// <param name="cancellationToken">取消请求的令牌。<br/>Token used to cancel the request.</param>
    public async Task DeleteTask(string taskId, CancellationToken cancellationToken = default)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(taskId);
        var parameters = new Dictionary<string, string> { { "taskID", taskId } };
        await netService.Post($"{BaseUrl}/deleteTask", parameters, ApiVersion.V2_10_4, ct : cancellationToken);
    }
}
