name: Build and Push NuGet Package

on:
    release:
        types: [published] # 只有发布（Publish）后才触发；创建草稿不会触发

jobs:
    build:
        runs-on: ubuntu-latest # Can be changed to windows-latest if needed

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up .NET
              uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: "8.0" # Adjust as per your project needs

            - name: Restore dependencies
              run: dotnet restore Banned.Qbittorrent/Banned.Qbittorrent.csproj

            - name: Build the project
              run: dotnet build Banned.Qbittorrent/Banned.Qbittorrent.csproj --configuration Release --no-restore

            - name: Pack the project
              run: dotnet pack Banned.Qbittorrent/Banned.Qbittorrent.csproj --configuration Release --no-build --output nupkg

            - name: Install xmllint
              run: |
                  sudo apt-get update && sudo apt-get install -y libxml2-utils
                  xmllint --version  # 检查 xmllint 是否成功安装

            - name: Extract version from .csproj
              id: extract_version
              run: |
                  VERSION=$(xmllint --xpath "string(//Project/PropertyGroup/Version)" Banned.Qbittorrent/Banned.Qbittorrent.csproj)
                  echo "version=$VERSION" >> $GITHUB_ENV

            - name: Push NuGet package
              run: |
                  NUPKG_FILE=$(find nupkg -name "Banned.Qbittorrent.$version.nupkg" -print -quit)
                  if [ -z "$NUPKG_FILE" ]; then
                    echo "Error: NuGet package not found!"
                    exit 1
                  fi
                  echo "Pushing $NUPKG_FILE to NuGet..."
                  dotnet nuget push "$NUPKG_FILE" --api-key ${{ secrets.NUGET_API_KEY }} --source "https://api.nuget.org/v3/index.json" --skip-duplicate
